name: Rails CI

on: [push]

env:
  RAILS_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Setup Ruby
        uses: actions/setup-ruby@v2.2.0
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: |
          bundle exec rails test